plugin: aws_ec2
regions:
  - ap-south-1
# keyed_groups may be used to create custom groups
strict: true
keyed_groups:
  # Add hosts to tag_Name_Value groups for each Name/Value tag pair
  - prefix: tag
    key: tags
hostnames:
  # - private-ip-address
  - ip-address